stages:
  - quality
  - build
  - deploy

quality_job:
  stage: quality
  image: python:latest
  script:
    - pip install -r requirements.txt
    - pylint pelicanconf.py publishconf.py

build_job:
  stage: build
  image: python:latest
  script:
    - pip install -r requirements.txt
    - make html
  artifacts:
    paths:
      - output/


deploy_job:
  stage: deploy
  image: python:latest
  script:
    - git clone https://github.com/flety/flety.github.io.git /tmp/flety.github.io
    - cp -rfp output/* /tmp/flety.github.io
    - cd /tmp/flety.github.io
    - git add -A
    - git commit -m "[Deploy] Deploy $(date)"
  when: manual
  artifacts:
    paths:
      - output/
