stages:
  - build
  - deploy

build_job:
  stage: build
  image: python:latest
  script:
    - pip install pelican
    - pip install markdown
    - make html

deploy_job:
  stage: deploy
  image: python:latest
  script:
    - echo "hi"